//! `theoria` — generate and serve a Leptos component gallery from a crate's
//! stories (the Storybook-style dev tool for theoria).
//!
//! It reads `theoria.toml`, **generates** a small Trunk app under
//! `target/theoria/gallery` that mounts `theoria::Gallery` with the configured
//! crate's `stories` aggregator, then runs Trunk on it. Nothing to hand-write or
//! commit — the gallery harness is generated on every run.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use serde::Deserialize;

#[derive(Parser)]
#[command(
    name = "theoria",
    version,
    about = "Generate and serve a Leptos component gallery"
)]
struct Cli {
    #[command(subcommand)]
    command: Cmd,
    /// Path to the theoria config file.
    #[arg(long, default_value = "theoria.toml", global = true)]
    config: PathBuf,
}

#[derive(Subcommand)]
enum Cmd {
    /// Generate the gallery harness and serve it with Trunk (hot reload).
    Serve {
        /// Port for the Trunk dev server.
        #[arg(long, default_value_t = 8081)]
        port: u16,
    },
    /// Generate the gallery harness and build it with Trunk.
    Build,
    /// Only generate the gallery harness (no Trunk).
    Generate,
}

#[derive(Deserialize)]
struct Config {
    gallery: GalleryConfig,
}

#[derive(Deserialize)]
struct GalleryConfig {
    /// Package name of the crate that exposes the stories (the dependency name).
    #[serde(rename = "crate")]
    krate: String,
    /// Path to that crate, relative to the config file.
    path: String,
    /// Fully-qualified fn returning `Vec<theoria::Story>`, e.g. `slp_ui::all_stories`.
    aggregator: String,
    /// Extra features to enable on the crate (csr is added automatically).
    #[serde(default)]
    features: Vec<String>,
    /// Path to the theoria crate, relative to the config file.
    #[serde(default = "default_theoria_path")]
    theoria_path: String,
}

fn default_theoria_path() -> String {
    "crates/theoria".to_string()
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    let config_path = cli
        .config
        .canonicalize()
        .with_context(|| format!("config not found: {}", cli.config.display()))?;
    let repo_root = config_path
        .parent()
        .context("config file has no parent directory")?
        .to_path_buf();
    let config: Config =
        toml::from_str(&fs::read_to_string(&config_path).context("read theoria.toml")?)
            .context("parse theoria.toml")?;

    // Per-crate output dir so different galleries (e.g. slp-ui vs theoria's own
    // e2e fixtures) don't clobber each other.
    let gallery_dir = repo_root
        .join("target/theoria/gallery")
        .join(&config.gallery.krate);
    generate(&repo_root, &gallery_dir, &config.gallery)?;
    println!("theoria: generated gallery at {}", gallery_dir.display());

    match cli.command {
        Cmd::Generate => Ok(()),
        Cmd::Build => trunk(&gallery_dir, &["build"]),
        Cmd::Serve { port } => {
            let port = port.to_string();
            trunk(&gallery_dir, &["serve", "--port", &port])
        }
    }
}

/// Write the generated Trunk gallery crate (`Cargo.toml`, `index.html`,
/// `src/main.rs`) into `dir`.
fn generate(repo_root: &Path, dir: &Path, g: &GalleryConfig) -> Result<()> {
    let target_abs = repo_root.join(&g.path);
    let theoria_abs = repo_root.join(&g.theoria_path);
    if !target_abs.join("Cargo.toml").exists() {
        bail!("no crate found at {}", target_abs.display());
    }

    let mut features = g.features.clone();
    if !features.iter().any(|f| f == "csr") {
        features.push("csr".to_string());
    }
    let feat_list = features
        .iter()
        .map(|f| format!("\"{f}\""))
        .collect::<Vec<_>>()
        .join(", ");

    // When the stories crate IS theoria (e.g. theoria's own e2e), emit a single
    // theoria dependency with the merged features — otherwise we'd write the
    // `theoria = ...` key twice (a duplicate-dependency error).
    let deps = if g.krate == "theoria" {
        format!(
            "theoria = {{ path = \"{theoria}\", features = [{feat_list}] }}\n",
            theoria = theoria_abs.display(),
        )
    } else {
        format!(
            "theoria = {{ path = \"{theoria}\", features = [\"csr\"] }}\n\
             {krate} = {{ path = \"{target}\", features = [{feat_list}] }}\n",
            theoria = theoria_abs.display(),
            krate = g.krate,
            target = target_abs.display(),
        )
    };

    let cargo_toml = format!(
        "# GENERATED by `theoria` — do not edit; regenerated on each run.\n\
         [package]\n\
         name = \"theoria-gallery\"\n\
         version = \"0.0.0\"\n\
         edition = \"2024\"\n\
         publish = false\n\n\
         [[bin]]\n\
         name = \"theoria-gallery\"\n\
         path = \"src/main.rs\"\n\n\
         [dependencies]\n\
         leptos = {{ version = \"0.8\", features = [\"csr\"] }}\n\
         console_error_panic_hook = \"0.1\"\n\
         {deps}\n\
         # Own workspace so it isn't absorbed by the parent repo's workspace.\n\
         [workspace]\n",
    );

    let main_rs = format!(
        "// GENERATED by `theoria` — do not edit.\n\
         use leptos::mount::mount_to_body;\n\
         use leptos::prelude::*;\n\n\
         fn main() {{\n    \
         console_error_panic_hook::set_once();\n    \
         mount_to_body(|| view! {{ <theoria::Gallery stories={aggregator}() /> }});\n\
         }}\n",
        aggregator = g.aggregator,
    );

    fs::create_dir_all(dir.join("src")).context("create gallery dir")?;
    fs::write(dir.join("Cargo.toml"), cargo_toml).context("write Cargo.toml")?;
    fs::write(dir.join("src/main.rs"), main_rs).context("write src/main.rs")?;
    fs::write(dir.join("index.html"), GALLERY_INDEX_HTML).context("write index.html")?;
    Ok(())
}

fn trunk(dir: &Path, args: &[&str]) -> Result<()> {
    let status = Command::new("trunk")
        .current_dir(dir)
        .args(args)
        .status()
        .context("failed to run `trunk` (install it with `cargo install trunk`)")?;
    if !status.success() {
        bail!("`trunk {}` failed", args.join(" "));
    }
    Ok(())
}

const GALLERY_INDEX_HTML: &str = r#"<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>theoria — component gallery</title>
    <link data-trunk rel="rust" data-wasm-opt="z" />
    <style>
      body { margin: 0; font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; background: #faf7f1; color: #2c2a25; }
      .theoria { display: flex; gap: 16px; padding: 16px 22px; align-items: flex-start; }
      .theoria-nav { flex: 0 0 160px; }
      .theoria-nav ul { list-style: none; margin: 0; padding: 0; }
      .theoria-nav button { display: block; width: 100%; text-align: left; padding: 6px 10px; margin: 2px 0; border: 1px solid #e3dccb; border-radius: 8px; background: #fff; cursor: pointer; font: inherit; font-size: 13px; }
      .theoria-nav button.active { background: #5c6b4f; color: #fff; border-color: #5c6b4f; }
      .theoria-stage { flex: 1 1 auto; background: #fff; border: 1px solid #e3dccb; border-radius: 12px; padding: 16px; min-height: 200px; }
    </style>
  </head>
  <body></body>
</html>
"#;
